[project]
name = 'Tokenized-Arts-Cultural-Heritage-Preservation'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.audience-engagement]
path = 'contracts/audience-engagement.clar'
clarity_version = 2
epoch = 2.5

[contracts.collaboration-platform]
path = 'contracts/collaboration-platform.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
